apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictionapp
  template:
    metadata:
      labels:
        app: predictionapp
    spec:
      containers:
        - name: predicitionapp
          image: sdrivert/prediction
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: predicitionapp-service
spec:
  selector:
    app: predicitionapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30900
  type: NodePort
