apiVersion: v1
kind: Service
metadata:
  name: ml-model-service
spec:
  selector:
    app: ml-model
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8000
      nodePort: 30000
  type: NodePort
